import pandas as pd
from pdb import set_trace as bp

def get_dummy_header():
    jobs_df = pd.read_csv('../EDA_data_result.csv')
    df_model = jobs_df[["Job Location", "Company Rating", "Company Rating Numbers", "Company Size", "Company Founded", "Company Type", 
                    "Company Industry", "Company Sector", "Company Revenue", "Level", "Currency", "Role"]]
    df_dum = pd.get_dummies(df_model)
    empty_dummy = pd.DataFrame(columns = df_dum.columns)
    empty_dummy.to_csv('dummy_header.csv')

def parset_input_data(input_data_path):
    # input_data_path is the path to input data csv file
    # input data must have the same format column as EDA_data_result.csv without maximum and minimum(ignore Company column with empty column)
    # Company related data must satisfy the glassdoor format for classification data
    # For role can be generated by based on role() function in Data Exploratory Analysis file (similar for level as well)

    dummy_header = pd.read_csv('dummy_header.csv').columns[1:]
    input_df = pd.read_csv(input_data_path)
    df_model = input_df[["Job Location", "Company Rating", "Company Rating Numbers", "Company Size", "Company Founded", "Company Type", 
                    "Company Industry", "Company Sector", "Company Revenue", "Level", "Currency", "Role"]]
    classification_cols = ["Job Location", "Company Size", "Company Type", "Company Industry", 
    "Company Sector", "Company Revenue", "Level", "Currency", "Role"]
    
    data_list = []
    for row_index in range(len(df_model)):
        row = df_model.loc[row_index]
        data = []
        for header in dummy_header:
            split_header = header.split('_')
            if split_header[0] in classification_cols:
                data.append(int(split_header[1] == row[split_header[0]]))
            else:
                data.append(int(row[header]))
        data_list.append(data)
    return data_list

